name: Auto-assign member to setup comms request

on:
  issues:
    types: [labeled]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'comms-request')
    steps:
      - name: Auto-assign issue
        uses: pozil/auto-assign-issue@v1
        with:
          assignees: dhy6785,13jkim,ellisPae,jessxu12,bkong18,GeminiReaper,sunny-kwon,samyooo
          numOfAssignee: 1
          allowSelfAssign: true
