name: Create Livestream Configuration Issue

on:
  schedule:
    - cron: "0 12 * * 5" # Every Friday at noon
  workflow_dispatch:

jobs:
  create_issues:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main
    steps:
      - name: Create Issue and Add to Project
        uses: actions/github-script@v7
        env:
          LIVESTREAM_ISSUE_ASSIGNEES: ${{ secrets.LIVESTREAM_ISSUE_ASSIGNEES }}
          PROJECT_ID: ${{ secrets.SUPPORT_ROTATION_PROJECT_ID }}
          ISSUE_TITLE: "🎬 Livestream Configuration Checklist"
          ISSUE_BODY: |
            **This is to ensure all livestream configurations are ready before Sunday Worship.**

            ---

            ### Guide for working on this task:

            - [Walkthrough for Documentation](https://docs.google.com/document/d/1a4TKKc_wzeZQpRmYtNluZuHA99PP38EJtcRtW_ildsg/edit?usp=sharing)

            ### Needed Links (open 'em all!):

            - [Restream.io dashboard](https://app.restream.io/channel)
            - [Sanity.io Studio dashboard](https://metrochurch.sanity.studio/desk/);

        with:
          github-token: ${{ secrets.PAUL_MASTER_KEY }}
          script: |
            const issueTitle = process.env.ISSUE_TITLE;
            const issueBody = process.env.ISSUE_BODY;
            const labels = ['support-rotation'];
            const assignees = process.env.LIVESTREAM_ISSUE_ASSIGNEES.split(',');

            // Create the issue
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: labels,
              assignees: assignees
            });

            // Add the issue to the project
            const projectId = process.env.PROJECT_ID;
            const contentId = issue.data.node_id;

            const query = `
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }
            `;

            await github.graphql(query, {
              projectId: projectId,
              contentId: contentId
            });

            console.log(`Created and added issue to project: ${issue.data.html_url}`);
