name: Auto-assign reviewer when support items move to "In Review"

on:
  issues:
    types: [labeled]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main
    if: contains(github.event.issue.labels.*.name, 'support-rotation')
    steps:
      - name: Create Issue and Add to Project
        uses: actions/github-script@v7
        env:
          PROJECT_ID: ${{ secrets.SUPPORT_ROTATION_PROJECT_ID }}

        with:
          github-token: ${{ secrets.PAUL_MASTER_KEY }}
          script: |
            const reviewer = $SUPPORT_REVIEWER
            const labels = ['support-rotation'];

            // 1. If any issue is moved the to "In Review" column of the PROJECT_ID, get that issue and tag the REVIEWER as an assignee
