name: Create Sermon Audio Process Issue

on:
  schedule:
    - cron: "0 16 * * 5" # Every Friday at noon
  workflow_dispatch:

jobs:
  create_issues:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main
    steps:
      - name: Create Issue and Add to Project
        uses: actions/github-script@v7
        env:
          ASSIGNEES: ${{ vars.SERMON_AUDIO_SCRUB_ISSUE_ASSIGNEES }}
          REVIEWERS: ${{ vars.SUPPORT_REVIEWERS }}
          PROJECT_ID: ${{ secrets.SUPPORT_ROTATION_PROJECT_ID }}
          ISSUE_TITLE: "Support: 🎙 Sermon Audio Process & Upload"

        with:
          github-token: ${{ secrets.PAUL_MASTER_KEY }}
          script: |
            const assignees = process.env.ASSIGNEES.split(",").map(a => a.trim());
            const reviewers = process.env.REVIEWERS.split(",").map(a => `@${a.trim()}`).join(" ");
            const labels = ['support-rotation'];

            const issueTitle = process.env.ISSUE_TITLE;
            const issueBody = `
            **This is to ensure the sermon audio is processed, scrubbed, and deployed to all podcast platforms and the website.**

            **Due: By Monday 11 PM**

            ---

            ### Guide for working on this task:

            - Clone and run the script at [https://github.com/metrophilly/sermon-processor](https://github.com/metrophilly/sermon-processor)

            - [Walkthrough for Documentation](https://docs.google.com/document/d/1E1Toca22oYXMhaz9miD8ygtUiUvyg4oU2EbFJIya3N8/edit?usp=sharing)

            ### Checklist

            - [ ] Process and scrub the sermon audio
              - [ ] Ensure that the file includes the closing prayer
            - [ ] Upload processed audiofile to S3 bucket
            - [ ] Update the "Sermon" document in Sanity to include the correct S3 path and deploy
            - [ ] When complete, shift card to "Ready to Review" and tag ${reviewers}
            `;

            // Create the issue
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: labels,
              assignees: assignees
            });

            // Add the issue to the project
            const projectId = process.env.PROJECT_ID;
            const contentId = issue.data.node_id;

            const query = `
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }
            `;

            await github.graphql(query, {
              projectId: projectId,
              contentId: contentId
            });

            console.log(`Created and added issue to project: ${issue.data.html_url}`);
