name: Create Post-Service Cleanup Issue

on:
  schedule:
    - cron: "0 16 * * 5" # Every Friday at noon
  workflow_dispatch:

jobs:
  create_issues:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main
    steps:
      - name: Create Issue and Add to Project
        uses: actions/github-script@v7
        env:
          PROJECT_ID: ${{ secrets.SUPPORT_ROTATION_PROJECT_ID }}
          ISSUE_TITLE: "Support: 🧹 Post-Service Media Cleanup"

        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = ['support-rotation'];

            const issueTitle = process.env.ISSUE_TITLE;
            const issueBody = `
            **This is to ensure all media cards are setup and ready for the week.**

            **Due: By Sunday 11 PM**

            ---

            ### Guide for working on this task:

            - [Post-Service Media Cleanup Walkthrough](https://docs.google.com/document/d/1NzRL9EhwmAUeHA0TT_mH2LCvOOw3PHdupisZ84ngkMM/edit?usp=sharing)

            ### Needed Links (open 'em all!):

            - [Sanity.io Studio dashboard](https://metrochurch.sanity.studio/desk/)
            - [Canva login](https://www.canva.com/)

            ### Checklist

            - [ ] Set Youtube video ID in Sanity Studio and deploy
            - [ ] Get the Livestream graphics image from the slack #graphics channel, & add to the Youtube video
            - [ ] Create Youtube timestamps, adjust the praise songs, passage, and sermon titles accordingly
            - [ ] When complete, shift card to "Ready to Review" and tag this week's reviewer

            cc: @paulhchoi
            `;

            // Create the issue
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: labels
            });

            // Add the issue to the project
            const projectId = process.env.PROJECT_ID;
            const contentId = issue.data.node_id;

            const query = `
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }
            `;

            await github.graphql(query, {
              projectId: projectId,
              contentId: contentId
            });

            console.log(`Created and added issue to project: ${issue.data.html_url}`);
