name: Create Livestream Configuration Issue

on:
  schedule:
    - cron: "0 17 * * 5" # Every Friday at noon
  workflow_dispatch:

jobs:
  create_issues:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main
    steps:
      - name: Create Issue and Add to Project
        uses: actions/github-script@v7
        env:
          ASSIGNEES: ${{ vars.LIVESTREAM_ISSUE_ASSIGNEES }}
          REVIEWERS: ${{ vars.SUPPORT_REVIEWERS }}
          PROJECT_ID: ${{ secrets.SUPPORT_ROTATION_PROJECT_ID }}
          ISSUE_TITLE: "Support: 🎬 Livestream Configuration Checklist"

        with:
          github-token: ${{ secrets.PAUL_MASTER_KEY }}
          script: |
            const assignees = process.env.ASSIGNEES.split(",").map(a => a.trim());
            const reviewers = process.env.REVIEWERS.split(",").map(a => `@${a.trim()}`).join(" ");
            const labels = ['support-rotation'];

            const issueTitle = process.env.ISSUE_TITLE;
            const issueBody = `
            **This is to ensure all livestream configurations are ready before Sunday Worship.**

            **Due: By Saturday 6 PM**

            ---

            ### Guide for working on this task:

            - [Livestream Configuration Walkthrough](https://docs.google.com/document/d/1a4TKKc_wzeZQpRmYtNluZuHA99PP38EJtcRtW_ildsg/edit?usp=sharing)

            ### Needed Links (open 'em all!):

            - [Restream.io dashboard](https://app.restream.io/channel)
            - [Sanity.io Studio dashboard](https://metrochurch.sanity.studio/desk/)

            ### Checklist

            - [ ] Update and confirm "Livestream Event" data in Sanity Studio is correct
            - [ ] Update Restream's "Social Alerts" content
            - [ ] When complete, shift card to "Ready to Review" and tag ${reviewers}
            `;

            // Create the issue
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: labels,
              assignees: assignees
            });

            // Add the issue to the project
            const projectId = process.env.PROJECT_ID;
            const contentId = issue.data.node_id;

            const query = `
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }
            `;

            await github.graphql(query, {
              projectId: projectId,
              contentId: contentId
            });

            console.log(`Created and added issue to project: ${issue.data.html_url}`);
